# More documentation about how to customize your build
# can be found here:
# https://docs.fastlane.tools
fastlane_version "2.68.0"

# This value helps us track success metrics for Fastfiles
# we automatically generate. Feel free to remove this line
# once you get things running smoothly!
generated_fastfile_id "9c79a3f1-aece-459f-8a83-4d4b2d13b44e"

default_platform :ios

# Fastfile actions accept additional configuration, but
# don't worry, fastlane will prompt you for required
# info which you can add here later
desc "Runs all the tests"
  lane :test do
    scan
    snapshot
  end
lane :beta do
  # build your iOS app
  build_app(
    scheme: "AutomationDemo",
    export_method: "app-store"
  )

  # upload to Testflight
  pilot(skip_waiting_for_build_processing: true)
end
